name: Build and Deploy TopList

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        check-latest: true

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build

    - name: List working directory contents
      run: ls -la

    - name: List build directory contents
      run: ls -la ./dist  # Adjust path if necessary

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
